on: 
    workflow_call:
      inputs:
        tag:
          description: 'The version tag to use for stamping build artifacts and naming generated archives'
          required: true
          type: string
        prerelease:
          description: 'Set to true if published build is a prerelease'
          type: boolean
          required: true
env:
  DOCKER_REPO: ghcr.io/${{ github.repository_owner }}/cxone/scan-scheduler
                
jobs:
  publish-scheduler:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Code @ tag ${{ inputs.tag }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: refs/tags/${{ inputs.tag }}

      - name: Update version
        run: |
            echo "__version__='${{ inputs.tag }}'" > __version__.py

      - name: Build and Push Docker Image
        run: |
          BRIEFTAG=${{ inputs.tag }}
          docker build -f Dockerfile -t $DOCKER_REPO:$BRIEFTAG .
          [ ${{ inputs.prerelease }} = false ] && docker tag $DOCKER_REPO:$BRIEFTAG $DOCKER_REPO:latest || :
          docker push --all-tags $DOCKER_REPO
  
  publish-release:
    runs-on: ubuntu-latest
    needs: [publish-scheduler]
    steps:
      - name: Fetch Code @ tag ${{ inputs.tag }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: refs/tags/${{ inputs.tag }}

      - name: Make release text
        run: |
          echo "# CxOne Scan Scheduler ${{ inputs.tag }}" > release.md
          echo Executable artifacts are published in a container that can be pulled locally and executed. >> release.md
          echo '```' >> release.md
          [ ${{ inputs.prerelease }} = false ] && echo "docker pull $DOCKER_REPO:latest" >> release.md || :
          echo "docker pull $DOCKER_REPO:${{ inputs.tag }}" >> release.md
          echo '```' >> release.md
          echo >> release.md
          echo "A Helm chart is also available as part of the release artifacts." >> release.md

      - name: Make Helm tgz
        run: |
          cat helm/Chart.yaml | sed -E "s/(appVersion:) \"DEV\"/\1 \"${{ inputs.tag}}\"/g" > helm/Chart.yaml.tmp
          rm helm/Chart.yaml
          mv helm/Chart.yaml.tmp helm/Chart.yaml
          tar -C ./helm -czf cxone-scan-scheduler_helm.tgz .

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          bodyFile: release.md
          name: ${{ inputs.tag }}
          prerelease: ${{ inputs.prerelease }}
          tag: ${{ inputs.tag }}
          artifacts: "*.tgz"


         