on: 
    workflow_call:
      inputs:
        tag:
          description: 'The version tag string'
          required: true
          type: string
        prerelease:
          description: 'Set to true if publishing a pre-release.'
          required: true
          type: boolean
              
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set Tag
        run: |
          git tag '${{ inputs.tag }}'
          git push origin '${{ inputs.tag }}'

        
  publish-release:
    needs: [create-tag]
    uses: ./.github/workflows/build.yml
    with:
      tag: ${{ inputs.tag }}
      prerelease: ${{ inputs.prerelease }}

  remove-tag-on-failure:
    needs: [create-tag, publish-release]
    runs-on: ubuntu-latest
    if: ${{ failure() || cancelled() }}
    steps:
      - name: Fetch Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Remove CodeTag
        run: git push origin ':refs/tags/${{ inputs.tag }}'
    
        
    
  
  
    