name: Publish a Release
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'The version tag to use in the form of x.x'
        required: true
        type: string
      prerelease:
        description: 'Check if this is to publish a pre-release.'
        required: true
        type: boolean
  
permissions:
  contents: read

jobs:
  make-tag-string:
    runs-on: cx-public-ubuntu-x64
    outputs:
      tag: ${{ steps.tag-string.outputs.tag }}
    steps:
      - name: Create tag string
        run: |
          [ ${{ inputs.prerelease }} = false ] && echo "tag=v${{ inputs.version }}" >> $GITHUB_OUTPUT || \
            echo "tag=v${{ inputs.version }}-$GITHUB_RUN_NUMBER-prerelease" >> $GITHUB_OUTPUT
        id: tag-string
      
  validate-no-tag:
    runs-on: cx-public-ubuntu-x64
    needs: [make-tag-string]
    steps:
      - name: Fetch Code
        continue-on-error: true
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: ${{ needs.make-tag-string.outputs.tag }}
      - name: Fail if tag ${{ needs.make-tag-string.outputs.tag }} exists
        run: |
          [[ $(git describe --tags) ==  ${{ needs.make-tag-string.outputs.tag }} ]] && exit 1 || :

  create-tag:
    needs: [make-tag-string, validate-no-tag]
    permissions:
      contents: write
    runs-on: cx-public-ubuntu-x64
    steps:
      - name: Fetch Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set Tag
        run: |
          git tag '${{ needs.make-tag-string.outputs.tag }}'
          git push origin '${{ needs.make-tag-string.outputs.tag }}'

  publish-release:
    needs: [create-tag, make-tag-string]
    runs-on: cx-public-ubuntu-x64
    steps:
    - name: force fail
      run: exit 1

  remove-tag-on-failure:
    needs: [create-tag, publish-release, make-tag-string]
    permissions:
      contents: write
    runs-on: cx-public-ubuntu-x64
    if: (failure() || cancelled()) && needs.create-tag.result == 'success'
    steps:
      - name: Fetch Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Remove tag
        run: git push origin ':refs/tags/${{ needs.make-tag-string.outputs.tag }}'


  # invoke-build-for-publish:
  #   needs: [make-tag-string, validate-no-tag]
  #   uses: ./.github/workflows/invoke-build.yml
  #   permissions:
  #     packages: write
  #     contents: write
  #   with:
  #     tag: ${{ needs.make-tag-string.outputs.tag }}
  #     prerelease: ${{ inputs.prerelease }}

